function out1 = f1(theta1)
%F1
%    OUT1 = F1(THETA1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Mar-2023 14:10:54

t2 = cos(theta1);
t3 = sin(theta1);
out1 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(4.0./5.0),t3.*(4.0./5.0),0.0,1.0],[4,4]);
