function out1 = f2(theta2)
%F2
%    OUT1 = F2(THETA2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Mar-2023 14:10:54

t2 = cos(theta2);
t3 = sin(theta2);
out1 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(3.0./5.0),t3.*(3.0./5.0),0.0,1.0],[4,4]);
