function out1 = f3(theta3)
%F3
%    OUT1 = F3(THETA3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    21-Mar-2023 14:10:54

t2 = cos(theta3);
t3 = sin(theta3);
out1 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(3.0./1.0e+1),t3.*(3.0./1.0e+1),0.0,1.0],[4,4]);
